# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mi_settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiSettingsDialog(object):
    def setupUi(self, MiSettingsDialog):
        MiSettingsDialog.setObjectName("MiSettingsDialog")
        MiSettingsDialog.resize(301, 319)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/property.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MiSettingsDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(MiSettingsDialog)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.options = QtWidgets.QWidget(MiSettingsDialog)
        self.options.setObjectName("options")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.options)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.options)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.options)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.queueSize = QtWidgets.QSpinBox(self.options)
        self.queueSize.setMaximum(100)
        self.queueSize.setObjectName("queueSize")
        self.gridLayout_3.addWidget(self.queueSize, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.options)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.discardOldest = QtWidgets.QCheckBox(self.options)
        self.discardOldest.setObjectName("discardOldest")
        self.gridLayout_3.addWidget(self.discardOldest, 2, 1, 1, 1)
        self.samplingInterval = QtWidgets.QSpinBox(self.options)
        self.samplingInterval.setMinimum(-1)
        self.samplingInterval.setMaximum(50000)
        self.samplingInterval.setSingleStep(100)
        self.samplingInterval.setObjectName("samplingInterval")
        self.gridLayout_3.addWidget(self.samplingInterval, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.options, 0, 0, 1, 3)
        self.dataChangeFilter = QtWidgets.QGroupBox(MiSettingsDialog)
        self.dataChangeFilter.setCheckable(True)
        self.dataChangeFilter.setChecked(False)
        self.dataChangeFilter.setObjectName("dataChangeFilter")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dataChangeFilter)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.dataChangeFilter)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.dataChangeTrigger = QtWidgets.QComboBox(self.dataChangeFilter)
        self.dataChangeTrigger.setObjectName("dataChangeTrigger")
        self.gridLayout_2.addWidget(self.dataChangeTrigger, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.dataChangeFilter)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.deadbandType = QtWidgets.QComboBox(self.dataChangeFilter)
        self.deadbandType.setObjectName("deadbandType")
        self.gridLayout_2.addWidget(self.deadbandType, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.dataChangeFilter)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.deadbandValue = QtWidgets.QDoubleSpinBox(self.dataChangeFilter)
        self.deadbandValue.setMaximum(999999999999999.0)
        self.deadbandValue.setObjectName("deadbandValue")
        self.gridLayout_2.addWidget(self.deadbandValue, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.dataChangeFilter, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 3)
        self.cancelButton = QtWidgets.QPushButton(MiSettingsDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 3, 2, 1, 1)
        self.addButton = QtWidgets.QPushButton(MiSettingsDialog)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 3, 1, 1, 1)

        self.retranslateUi(MiSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(MiSettingsDialog)

    def retranslateUi(self, MiSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        MiSettingsDialog.setWindowTitle(_translate("MiSettingsDialog", "Monitored Item Settings"))
        self.label.setText(_translate("MiSettingsDialog", "Sampling Interval"))
        self.label_2.setText(_translate("MiSettingsDialog", "Queue Size"))
        self.label_3.setText(_translate("MiSettingsDialog", "Discard Oldest"))
        self.dataChangeFilter.setTitle(_translate("MiSettingsDialog", "Data Change Filter"))
        self.label_4.setText(_translate("MiSettingsDialog", "Data Change Trigger"))
        self.label_5.setText(_translate("MiSettingsDialog", "Deadband Type"))
        self.label_6.setText(_translate("MiSettingsDialog", "Deadband Value"))
        self.cancelButton.setText(_translate("MiSettingsDialog", "Cancel"))
        self.addButton.setText(_translate("MiSettingsDialog", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiSettingsDialog = QtWidgets.QDialog()
    ui = Ui_MiSettingsDialog()
    ui.setupUi(MiSettingsDialog)
    MiSettingsDialog.show()
    sys.exit(app.exec_())
